const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
      version: "1.0.0",
      title: "My API",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
      {
          "name": "User",
          "description": "Endpoints"
      }
  ],
}

const outputFile = './swagger_output.json';
const endpointsFiles = ['./src/routes/app.routes.ts'];

swaggerAutogen(outputFile, endpointsFiles, doc);